[alembic]
script_location = alembic

sqlalchemy.url = postgresql://postgres:4110@localhost:5432/hrm_db


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
level = NOTSET
formatter = generic
args = (sys.stdout,)

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
