"""add employee_name to attendance

Revision ID: 2883bc91f16a
Revises: 5bcb8d69789f
Create Date: 2026-04-02 18:23:52.391495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2883bc91f16a'
down_revision: Union[str, Sequence[str], None] = '5bcb8d69789f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('employee_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'employee_name')
    # ### end Alembic commands ###
