"""nominee and pf ins add

Revision ID: 2a9280096526
Revises: 2883bc91f16a
Create Date: 2026-04-09 11:43:02.772791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9280096526'
down_revision: Union[str, Sequence[str], None] = '2883bc91f16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dependents_id'), table_name='dependents')
    op.drop_table('dependents')
    op.add_column('PayRoll', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('PayRoll', sa.Column('payFrequency', sa.String(), nullable=True))
    op.add_column('PayRoll', sa.Column('annualSalary', sa.Float(), nullable=True))
    op.add_column('PayRoll', sa.Column('monthlySalary', sa.Float(), nullable=True))
    op.add_column('PayRoll', sa.Column('EPF', sa.Float(), nullable=True))
    op.add_column('PayRoll', sa.Column('EPS', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('apply_esi', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('uan_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('pf_id', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('insurance_no', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('aadhar_no', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('esi_no', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('esi_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('insurance_provider', sa.String(), nullable=True))
    op.drop_column('employees', 'position')
    op.drop_column('employees', 'company_name')
    op.drop_column('employees', 'ToDate')
    op.drop_column('employees', 'FromDate')
    op.add_column('nominee', sa.Column('family_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nominee', 'Familys', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nominee', type_='foreignkey')
    op.drop_column('nominee', 'family_id')
    op.add_column('employees', sa.Column('FromDate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('ToDate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'insurance_provider')
    op.drop_column('employees', 'esi_name')
    op.drop_column('employees', 'esi_no')
    op.drop_column('employees', 'aadhar_no')
    op.drop_column('employees', 'insurance_no')
    op.drop_column('employees', 'pf_id')
    op.drop_column('employees', 'uan_number')
    op.drop_column('employees', 'apply_esi')
    op.drop_column('PayRoll', 'EPS')
    op.drop_column('PayRoll', 'EPF')
    op.drop_column('PayRoll', 'monthlySalary')
    op.drop_column('PayRoll', 'annualSalary')
    op.drop_column('PayRoll', 'payFrequency')
    op.drop_column('PayRoll', 'currency')
    op.create_table('dependents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('person_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relationship_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('person_dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.Emp_id'], name=op.f('dependents_emp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dependents_pkey'))
    )
    op.create_index(op.f('ix_dependents_id'), 'dependents', ['id'], unique=False)
    # ### end Alembic commands ###
