"""add status column to employees

Revision ID: 5bcb8d69789f
Revises: 01d063870dac
Create Date: 2026-04-02 18:07:01.224212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcb8d69789f'
down_revision: Union[str, Sequence[str], None] = '01d063870dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('check_in', sa.String(), nullable=True))
    op.add_column('attendance', sa.Column('check_out', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'check_out')
    op.drop_column('attendance', 'check_in')
    # ### end Alembic commands ###
