"""add_id_to_payroll_tables

Revision ID: 6e55d3d88293
Revises: 788c979ef90b
Create Date: 2026-04-14 16:20:06.957596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e55d3d88293'
down_revision: Union[str, Sequence[str], None] = '788c979ef90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_Payroll_id'), table_name='payroll')
    op.drop_table('payroll')
    op.drop_table('deductions')
    op.drop_index(op.f('ix_PayRollProviders_id'), table_name='PayRollProviders')
    op.drop_index(op.f('ix_PayRollProviders_provider_id'), table_name='PayRollProviders')
    op.drop_table('PayRollProviders')
    op.drop_table('earnings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id_fk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id_fk'], ['PayRollProviders.provider_id'], name=op.f('earnings_provider_id_fk_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('earnings_pkey'))
    )
    op.create_table('PayRollProviders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('providername', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PayRollProviders_pkey'))
    )
    op.create_index(op.f('ix_PayRollProviders_provider_id'), 'PayRollProviders', ['provider_id'], unique=True)
    op.create_index(op.f('ix_PayRollProviders_id'), 'PayRollProviders', ['id'], unique=False)
    op.create_table('deductions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id_fk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id_fk'], ['PayRollProviders.provider_id'], name=op.f('deductions_provider_id_fk_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deductions_pkey'))
    )
    op.create_table('payroll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Payroll_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('annualSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthlySalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['employees.Emp_id'], name=op.f('payroll_Emp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_pkey'))
    )
    op.create_index(op.f('ix_payroll_Payroll_id'), 'payroll', ['Payroll_id'], unique=False)
    # ### end Alembic commands ###
