"""initial

Revision ID: 73395b9b4433
Revises: 
Create Date: 2026-04-02 11:21:36.986423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73395b9b4433'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependents', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('education', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'Emp_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'Emp_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('education', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dependents', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
