"""add_id_to_payroll_tables

Revision ID: 788c979ef90b
Revises: fb04ff5b7952
Create Date: 2026-04-14 15:20:38.480456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788c979ef90b'
down_revision: Union[str, Sequence[str], None] = 'fb04ff5b7952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll')
    op.drop_table('earnings')
    op.drop_table('deductions')
    op.drop_table('PayRollProviders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PayRollProviders',
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('providername', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('provider_id', name=op.f('PayRollProviders_pkey'))
    )
    op.create_table('deductions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PayRollProvider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PayRollProvider_id'], ['PayRollProviders.provider_id'], name=op.f('deductions_PayRollProvider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deductions_pkey'))
    )
    op.create_table('earnings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PayRollProvider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PayRollProvider_id'], ['PayRollProviders.provider_id'], name=op.f('earnings_PayRollProvider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('earnings_pkey'))
    )
    op.create_table('payroll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('annualSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthlySalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['employees.Emp_id'], name=op.f('payroll_Emp_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['PayRollProviders.provider_id'], name=op.f('payroll_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_pkey'))
    )
    # ### end Alembic commands ###
