"""candidate schema update v2

Revision ID: 935db1e717a3
Revises: 2afeb868c66d
Create Date: 2026-05-13 12:12:59.248607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '935db1e717a3'
down_revision: Union[str, Sequence[str], None] = '2afeb868c66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stagelist_id'), table_name='stagelist')
    op.drop_table('stagelist')
    op.drop_index(op.f('ix_stage_details_Stage_id'), table_name='stage_details')
    op.drop_index(op.f('ix_stage_details_id'), table_name='stage_details')
    op.drop_table('stage_details')
    op.drop_index(op.f('ix_interview_Interview_id'), table_name='interview')
    op.drop_index(op.f('ix_interview_id'), table_name='interview')
    op.drop_table('interview')
    op.add_column('candidates', sa.Column('Candidate_code', sa.String(), nullable=True))
    op.execute('UPDATE candidates SET "Candidate_code" = "Candidate_id"')
    op.alter_column('candidates', 'Candidate_code', nullable=False)
    op.alter_column('candidates', 'Candidate_Skills',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'Candidate_Source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'Resume_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'Status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_candidates_Candidate_id'), table_name='candidates')
    op.create_unique_constraint(None, 'candidates', ['Candidate_code'])
    op.drop_column('candidates', 'Candidate_id')
    op.create_unique_constraint(None, 'employees', ['Emp_id'])
    op.add_column('leavehistory', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leavehistory_id'), 'leavehistory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leavehistory_id'), table_name='leavehistory')
    op.drop_column('leavehistory', 'id')
    op.drop_constraint(None, 'employees', type_='unique')
    op.add_column('candidates', sa.Column('Candidate_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='unique')
    op.create_index(op.f('ix_candidates_Candidate_id'), 'candidates', ['Candidate_id'], unique=True)
    op.alter_column('candidates', 'Status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'Resume_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'Candidate_Source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'Candidate_Skills',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('candidates', 'Candidate_code')
    op.create_table('interview',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Interview_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Candidate_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Interview_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('Interview_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('Interview_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Candidate_feedback', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('Stage_status', sa.VARCHAR(), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('Interviewer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Interview_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Interviewer_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Final_decision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Selected_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Candidate_id'], ['candidates.Candidate_id'], name=op.f('interview_Candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_pkey'))
    )
    op.create_index(op.f('ix_interview_id'), 'interview', ['id'], unique=False)
    op.create_index(op.f('ix_interview_Interview_id'), 'interview', ['Interview_id'], unique=True)
    op.create_table('stage_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Candidate_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Stage_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Stage_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Stage_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Candidate_id'], ['candidates.Candidate_id'], name=op.f('stage_details_Candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stage_details_pkey'))
    )
    op.create_index(op.f('ix_stage_details_id'), 'stage_details', ['id'], unique=False)
    op.create_index(op.f('ix_stage_details_Stage_id'), 'stage_details', ['Stage_id'], unique=True)
    op.create_table('stagelist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Stage_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stagelist_pkey'))
    )
    op.create_index(op.f('ix_stagelist_id'), 'stagelist', ['id'], unique=False)
    # ### end Alembic commands ###
