"""add_id_to_payroll_tables

Revision ID: fb04ff5b7952
Revises: 2e8fcc621651
Create Date: 2026-04-14 12:47:30.153212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb04ff5b7952'
down_revision: Union[str, Sequence[str], None] = '2e8fcc621651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings')
    op.drop_index(op.f('ix_payroll_Payroll_id'), table_name='payroll')
    op.drop_table('payroll')
    op.drop_index(op.f('ix_payRoll_Payroll_id'), table_name='payRoll')
    op.drop_table('payRoll')
    op.drop_table('deductions')
    op.drop_table('PayRollProviders')
    op.drop_index(op.f('ix_PayRoll_id'), table_name='PayRoll')
    op.drop_table('PayRoll')
    op.drop_index(op.f('ix_paypoll_Payroll_id'), table_name='paypoll')
    op.drop_table('paypoll')
    op.alter_column('Familys', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_Work_id'), table_name='Work')
    op.drop_column('Work', 'id')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_column('attendance', 'id')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_column('employees', 'id')
    op.drop_index(op.f('ix_leave_id'), table_name='leave')
    op.drop_column('leave', 'id')
    op.drop_index(op.f('ix_leavehistory_id'), table_name='leavehistory')
    op.drop_column('leavehistory', 'id')
    op.drop_index(op.f('ix_nominee_id'), table_name='nominee')
    op.drop_column('nominee', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nominee', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_nominee_id'), 'nominee', ['id'], unique=False)
    op.add_column('leavehistory', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_leavehistory_id'), 'leavehistory', ['id'], unique=False)
    op.add_column('leave', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_leave_id'), 'leave', ['id'], unique=False)
    op.add_column('employees', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.add_column('attendance', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.add_column('Work', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_Work_id'), 'Work', ['id'], unique=False)
    op.alter_column('Familys', 'emp_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('paypoll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Payroll_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('annualSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthlySalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['employees.Emp_id'], name=op.f('paypoll_Emp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paypoll_pkey'))
    )
    op.create_index(op.f('ix_paypoll_Payroll_id'), 'paypoll', ['Payroll_id'], unique=False)
    op.create_table('PayRoll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payFrequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('annualSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthlySalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('EPF', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('EPS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['employees.Emp_id'], name=op.f('PayRoll_Emp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('PayRoll_pkey'))
    )
    op.create_index(op.f('ix_PayRoll_id'), 'PayRoll', ['id'], unique=False)
    op.create_table('PayRollProviders',
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('providername', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('provider_id', name=op.f('PayRollProviders_pkey'))
    )
    op.create_table('deductions',
    sa.Column('PayRollProvider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PayRollProvider_id'], ['PayRollProviders.provider_id'], name=op.f('deductions_PayRollProvider_id_fkey')),
    sa.PrimaryKeyConstraint('PayRollProvider_id', name=op.f('deductions_pkey'))
    )
    op.create_table('payRoll',
    sa.Column('Payroll_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('annualSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthlySalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['employees.Emp_id'], name=op.f('payRoll_Emp_id_fkey')),
    sa.PrimaryKeyConstraint('Payroll_id', name=op.f('payRoll_pkey'))
    )
    op.create_index(op.f('ix_payRoll_Payroll_id'), 'payRoll', ['Payroll_id'], unique=False)
    op.create_table('payroll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Payroll_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Emp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('annualSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthlySalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emp_id'], ['employees.Emp_id'], name=op.f('payroll_Emp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_pkey'))
    )
    op.create_index(op.f('ix_payroll_Payroll_id'), 'payroll', ['Payroll_id'], unique=False)
    op.create_table('earnings',
    sa.Column('PayRollProvider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PayRollProvider_id'], ['PayRollProviders.provider_id'], name=op.f('earnings_PayRollProvider_id_fkey')),
    sa.PrimaryKeyConstraint('PayRollProvider_id', name=op.f('earnings_pkey'))
    )
    # ### end Alembic commands ###
